### ISSUE TITLE
Use the current working directory rather than AppContext.BaseDirectory

### ISSUE THREAD

**Issue by hadibrais** [mellinoe/ge#2]
The `AppContext.BaseDirectory` property returns the directory in which the currently main executable resides. This is the CLR host executable. However, I wanted to use a different host or runtime, `AppContext.BaseDirectory` will return the directory of that host. This will cause the code to crash due to FileNotFound exceptions. Instead of using `AppContext.BaseDirectory`, `System.IO.Directory.GetCurrentDirectory()` should be used.

**Comment by mellinoe** [comment]
Generally speaking, `AppContext.BaseDirectory` should point to the folder containing the managed entry point assembly, not the CLR host. It is used here to locate asset which are expected to be next to that file. What host are you using that causes it to point somewhere else?

The current directory is not what should be used here, because that is dependent on which folder you launched your application from... launch it from the wrong folder and it will no longer work.

**Comment by hadibrais** [comment]
I want to use corerun. The path to corerun is in PATH and so I can be at the directory in which the assets exist and launch the game using corerun. This will work if GetCurrentDirectory is used instead of  BaseDirectory. In addition, launching the game using the default host would still work. Using the directory of the main DLL is also fine.

**Comment by mellinoe** [comment]
Like I said, `GetCurrentDirectory` will only work sometimes, because it's based on where you launched the program from. If corerun isn't setting `AppContext.BaseDirectory` (it's controlled by the host), then I would probably consider that a bug. corerun isn't used that much outside of testing scenarios, so it's possible that it doesn't do the right thing there.

**Comment by hadibrais** [comment]
According the documentation, AppContext.BaseDirectory is the directory where the assembly manager begins probing for assemblies. This is the directory of the main executable of the process, which is the CLR host. corerun or any host is not the one who is setting the value of AppContext.BaseDirectory, it is the CLR and it does that during AppDomain setup. Using AppContext.BaseDirectory to find the assets does not make much sense since there is no relationship between the CLR host and the assets of the game.

If you don't want to use GetCurrentDirectory, you can use the directory in which CrazyCore.dll resides. This is fine too.

**Comment by mellinoe** [comment]
> AppContext.BaseDirectory is the directory where the assembly manager begins probing for assemblies

I think that description is a little bit misleading. The purpose of `AppContext.BaseDirectory` is to give you a location representing the "base path" of the actual application being run. Giving you the location of the native host isn't very useful, IMO. It is most likely a bug that `corerun` does not correctly set it to the directory containing the entry point assembly, since the regular host, dotnet(.exe), does set it. Like I said, `corerun` isn't really used a ton outside of CoreCLR testing, as far as I know. So this difference might have just fallen through the cracks.

**Comment by hadibrais** [comment]
The only reason that the precompiled binaries from your [blog post](https://mellinoe.wordpress.com/2017/01/18/net-core-game-engine/) work is because the host is in the same directory as the assets.

The dotnet host and any other host has nothing to do with AppContext.BaseDirectory. It is the runtime (libcoreclr.so) that sets the value of that property.

The current implementation of AppContext.BaseDirectory may not make a lot of sense. Perhaps, it would be better if it returned the directory of the binary that contains the Main method (the entry point). In fact, this makes the behavior on the .NET Framework and .NET Core more coherent. I'll raise this issue in the CoreCLR repo.

**Comment by hadibrais** [comment]
The CoreCLR issue is [here](https://github.com/dotnet/coreclr/issues/10998).

**Comment by mellinoe** [comment]
>Perhaps, it would be better if it returned the directory of the binary that contains the Main method (the entry point).

Sorry if I miscommunicated. I'm saying that this is what it does. This is the "entry point assembly". `dotnet.exe` does not return the folder containing `dotnet.exe`, it returns the folder containing the managed entry point. `corerun` does not, but that's probably just because it's mainly used for testing, not rigorous scenarios like this.

**Comment by AlexGhiondea** [comment]
I agree with @mellinoe. I believe you are going to get the value of your managed executable that contains the entry point. 

There might be a bug in corerun if it does not set the path as the path to the managed executable.
