### ISSUE TITLE
Transformed Postion

### ISSUE THREAD

**Issue by fls-eugene** [mellinoe/ge#4]
Hallo

I am busy learning about Transformations, however, finding a sensible sample has been a nightmare. Your class is helping already, thanks. 

Looking at the Position property In the src/Engine/Transform.cs. If I read it correctly, the getter uses the whole Transformation while the setter only does an offset when there is a parent?

Getter: 'pos = Vector3.Transform(pos, Parent.GetWorldMatrix());' // Includes parent's transformation
Setter '_localPosition = value - parentPos; // rotations and scale is lost?

**Comment by mellinoe** [comment]
Hey, sorry for the lack of response. I had been meaning to get back to you on this.

The reason it is done this way is because i wanted the `Position` setter to actually work in global space. If i call `box.Position = new Vector3(1, 2, 3);`, it shouldn't matter what `box`'s place in the Transform hieararchy is -- it should just be placed at `(1, 2, 3)`.

This is how Unity engine behaves, so it seemed intuitive enough to me.
