### ISSUE TITLE
Veldrid 2

### ISSUE THREAD

**Issue by darrylryan** [mellinoe/ge#5]
Hey there @mellinoe! Great work you're doing here. Do you intend to update the game engine to work with Veldrid 2 or has your focus shifted to just making a really good renderer now?

**Comment by mellinoe** [comment]
I am planning to make a game with the new Veldrid, but I'm not sure how much of the old game engine's graphics code I will retain. Part of me does want to update just the graphics code, just for fun, but another part of me wants to rewrite it and move on 😄 .

**Comment by Krakean** [comment]
@mellinoe 
Well, its still not bad project to learn how to work with Veldrid2 & other mix of your projects like ImGUI.Net and others. So please, when you will have some time, update this repo to latest versions of your components, to make it at least compilable & non-crashable with latest versions :)
Same for CrazyCore.

**Comment by ShalokShalom** [comment]
The version in Veldrids own release page says 4?

**Comment by mellinoe** [comment]
This engine uses the library that now lives [here](https://github.com/mellinoe/Veldrid-Legacy). I've since completely rewritten Veldrid and the old version is 100% obsolete in essentially all ways. But it is non-trivial to port the entire engine to the new library, so I'm not going to be spending time on that.

**Comment by ShalokShalom** [comment]
Ah, I see, thats why the name. You might want to mention this in the old repo and archive it
