### ISSUE TITLE
Upgrade code for latest version of Veldrid

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [mellinoe/ge#9]
Hello,
please upgrade the game engine to the latest version of Veldrid. It would be the best if it worked with Veldrid nugets etc.

**My Problem**
I need a light portable "game" engine for my robot research project. It is mobile robot that needs to imagine what he sees (camera, sensors, ...). So I need to simulate environment around the robot on robot's hardware (UP board with Linux) + something to visualise actual robot body state and its orientation and what robot imagines on Windows 10 PC. Unfortunately I do not have the experience or the time to create such a engine myself. Your game engine is more than sufficient for my task.

I can modify your game engine but it is not documented so I need your advises or a cookbook. I do not know how to create my own "game" and how to run it. This Game Engine does not work with Veldrid nuget packages and/or I do not know How to run Crazy Core (with Visual Studio or cli tools).

**Comment by eLEcTRiCZiTy** [comment]
I've read closed issues. Refactoring the entire engine 1:1 to the new Veldrid is not necessary. It is only necessary to give a course How to develop engine with Veldrid. Even less experienced users can get started and the community can expand. There is definitely no need to keep backward compatibility.

For me, the following is essential and it is not so difficult for creator/developer of Veldrid (from more important to less):
1. Modular system of logical functions like GameSystem and SystemRegister or simmilar looks good for further development.
2. Creating game objects that can be updated (hold game logic) and rendered. Scenes are not necessary but sample is useful.
3. Game objects can be linked to a parent-child relationship. When transforming a parent (translation, rotation, etc.), the children are transformed too. This can be achieved by game logic in update method. So parent must be able to read the properties of its children and vice versa.
4. Loading 3D models from files. Sample of parsing OBJ file into mesh and material into VisualModel that can be assigned to game object is sufficient.
5. The state of game objects can be serialized to something and deserialized. To achieve this function only the system to take snapshot of the World + game object interface for serialization/deserialization is necessary. User can implement serialization method (json, ...) itself.
6. Light sources can be only point light or cone or something. Sample of Veldrid usage is sufficient.
7. Audio can be positional (from game object) or environmental. Sample is sufficient.
8. Input handler as sample is sufficient too.

Live Editor etc. is not necessary. It can be community developed.

This should be a nice simple toolkit and an example of how to develop the engine further.

I can contribute if needed and if I know how.

**Comment by mellinoe** [comment]
Sorry, but I don't have any plans to work on this engine at all anymore. It's quite old at this point, and I've moved on to a lot of other projects since, including a newer game engine (not open source). Spending any time on this would detract a lot from my other projects, which I already struggle to make enough time for.

But, all the code is here, and you are free to fork it and use it for whatever you'd like. Keep in mind that this was mostly just a personal hobby project for fun and research -- it's not particularly robust or cutting-edge.

**Comment by eLEcTRiCZiTy** [comment]
Ok, so It looks like Crazy Core and it's engine was just a honeypot for headhunters.

I apologize for the longer text, but I need to explain why Veldrid now seems to be useless for people like me.

Veldrid is not exactly documented and its immature. The API is documented but it is useless for someone who does not know how to write something similar on its own. So why to use Veldrid if you can write something over which you have control. If you do not want to spend time for development then You can use Unity for example. Unity is portable, but too complex, but mature. Unity looks more stable and usable than Veldrid, although Veldrid looks best for every lightweight portable task. If there was a simple engine for Veldrid then Veldrid would be the first-choice tool.

If you want people to use your product. You have to show them how and why they should do it. Simple examples are good for someone like you. There is still no demonstration of how it should be used in the "real world" project for non-gameengine developer. Ok, there is very good demonstration - Crazy Core - but it does not work. Its written for old outdated version of Veldrid. So It is as if it did not exist.

Yes, your code is opensource. So I can spend lot of time to write something simmilar to your game engine with new version of Veldrid. I have no experience with game engine development even with simple one. I am specialist in embedded and cloud technology and robotics. So I don't know how to start with it. It will take a lot of time (maybe months). What if you then decide to change your mind on opensource project Veldrid and you will drop it too? Then I have to drop all my projects on which I spent a lot of time and money because of this. Without understanding how Veldrid works I must continue development of it on my own. But I have a little experience with Veldrid development so It will be useless too. This is huge dealbreaker even if it is an opensource. Sorry.

**Comment by mellinoe** [comment]
To reiterate, this project here is really old, and for me it has been superceded by a lot of newer projects, ones that I have since invested a lot more time and care into. For me, this project was just a fun experiment in 3D graphics and game development that I wanted to share with others, not something I planned to continuously improve for years. As a corollary to that, this project isn't relevant for learning about "new Veldrid". Crazy Core was built with the precursor-to-the-precursor to the current version of Veldrid. It's basically an entirely different library, one which I developed while still learning the fundamentals of 3D graphics. If you want to learn Veldrid, then I agree that this isn't the place to look.

Finally, I don't think anyone would argue that Veldrid's documentation and sample projects are perfect, or even in the same ball park as something like Unity. By comparison, though, they have entire teams of people working on documentation and sample projects. I work on improving Veldrid's documentation constantly, spending long hours of my own time, but I'm still just one person building an open source project. If there's one area of Veldrid that I want to improve the most, it's the documentation and new-user experience. At the same time, those are the things that I need the most help with, because my time is limited, and it takes away from adding new features and bug fixes to the library itself. It's a very difficult balance to get right.
